### ISSUE TITLE
GPUs turn off but seems still keep going Hash and get shares

### ISSUE THREAD

**Issue by 76badrinath** [mozkomor/GrinGoldMiner#38]
Config: 6x1070 GTX 8GB, mining with grin gold miner RC1 (lastest release )  on windows 10, 4Go Ram, 48 Go vrma, mining on grinmint. I got this after 20 minutes of mining ( 20 minutes with GPUs online ), miner say GPUs  offline, but hashrate and share show still running , any ideas ? pool dashboard say my worker is not offline ..  
logs:   
* ERROR, Listen errorUnable to find assembly 'ManagedCuda, Version=9.1.300.0, Culture=neutral, PublicKeyToken= /   
* errorThe input stream is not a valid binary format....

![issue grin gold miner](https://user-images.githubusercontent.com/46675093/51110576-7c3a4580-17f9-11e9-96f5-be28cd8983a7.png)

**Comment by phooton** [comment]
Grinmint is sending exactly same fake job over and over and miner goes offline and will turn-off cards after 30 minutes. This is grinmint issue not GGM. Try different pool.

**Comment by 76badrinath** [comment]
ok, thx for this quick answer, will try it

**Comment by d0n13** [comment]
I noticed this problem. Will this go away once mainnet starts up?

**Comment by zavis78** [comment]
+ one more thing, devs fee on grinmint pool,so doesn't matter on wich pool you connected,after 20 minutes its switch to mint and stays there forever.

**Comment by urza** [comment]
> * one more thing, devs fee on grinmint pool,so doesn't matter on wich pool you connected,after 20 minutes its switch to mint and stays there forever.

Can you please elaborate what do you mean by 20 minutes? What exactly is the sequence of events happening to you?

**Comment by donie-inhance** [comment]
![image](https://user-images.githubusercontent.com/12997313/51140442-79157880-183e-11e9-9452-e34c7a26697d.png)

I think the miner stops after 20 minutes. That's what it does for me. Shows as OFFLINE in red for both my 1080ti's. It does show as connected though and last job updates every few seconds.

Will this restart mining once main net goes live or do I need to restart after it goes live? Just that the go live time is 3am in my part of the world.

**Comment by urza** [comment]
Fixed in RC3 by special treatment of fake blocks form grinmint pool.

**Comment by donie-inhance** [comment]
The RC3 version connects and disconnects. Doesn't start mining for me. Do we still have an issue?
